name: Moodle plugin checks

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v4
        with:
          repository: EduardoKrausME/moodle-plugin-validate
          ref: master
          path: .moodle-plugin-validate
      - name: PHP lint
        run: find . -path './.moodle-plugin-validate' -prune -o -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Moodle plugin finishing validation
        run: python3 .moodle-plugin-validate/.chatgpt/run.py --check "$GITHUB_WORKSPACE"
